name: Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:lib

      - name: Prepare package
        run: npm run prepare:package

      - name: Publish to npm (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: cd dist/nsc && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build demo app
        run: npm run build:demo

      # You can add steps for deploying the demo app to GitHub Pages or another hosting provider 